version: '3.8'
services:
  library-service:
    build: .
    ports:
      - "8086:8080"
    network_mode: "host"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/Course-Service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
