apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-service
spec:
  selector:
    matchLabels:
      app: learner-service
  replicas: 1
  template:
    metadata:
      labels:
        app: learner-service
    spec:
      containers:
        - name: learner-service
          image: learner-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
