spring:
  data:
    mongodb:
      uri: mongodb+srv://HansakaJS:hansaka123@cluster0.cbz0c3m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: University-Timetable-Management-System
  main:
    banner-mode: off
server:
    port: 8085
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0